### ISSUE TITLE
Installation of Pirrot breaks PI Zero W OS

### ISSUE THREAD

**Issue by ComputerCarsten** [allebb/pirrot#58]
Hi,
today i tried to install pirrot on a Raspberri PI Zero W V1.1 with freshly installed 
"Raspberry Pi OS (Legacy, 32-bit) Lite" (2023-12-05) from the Pi imager 1.8.4.
At the end every thing breaks with "invalid instruction".
After the installation most commands don't work, even
```
$ reboot now
```
fails with an "invalid instruction".
After power-cycling the Pi Zero won't come up again (can't be ping'ed anymore).
I followed the installations instructions on the github page.
I guess there are some libraries overwritten with ones for the wrong ARM architecture.

**Comment by allebb** [comment]
Hey @ComputerCarsten, I've released a new version (v3.5.0) this morning. Please could you re-attempt the installation again and let me know how it goes for you?

**Comment by ComputerCarsten** [comment]
Hi

The problem is still there.
Here the output copied from putty
```
login as: pi
pi@192.168.1.209's password:
Linux pirrot 6.1.21+ #1642 Mon Apr  3 17:19:14 BST 2023 armv6l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
pi@pirrot:~ $ sudo apt-get install -y git
sudo git clone --single-branch --branch latest-stable https://github.com/allebb/pirrot /opt/pirrot
cd /opt/pirrot
sudo make install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  git-man liberror-perl
Suggested packages:
  git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk
  gitweb git-cvs git-mediawiki git-svn
The following NEW packages will be installed:
  git git-man liberror-perl
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 6,564 kB of archives.
After this operation, 33.1 MB of additional disk space will be used.
Get:1 http://mirror.netzwerge.de/raspbian/raspbian bullseye/main armhf liberror-perl all 0.17029-1 [31.0 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf git-man all 1:2.30.2-1+deb11u2 [1,828 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf git armhf 1:2.30.2-1+deb11u2 [4,704 kB]
Fetched 6,564 kB in 4s (1,680 kB/s)
Selecting previously unselected package liberror-perl.
(Reading database ... 43920 files and directories currently installed.)
Preparing to unpack .../liberror-perl_0.17029-1_all.deb ...
Unpacking liberror-perl (0.17029-1) ...
Selecting previously unselected package git-man.
Preparing to unpack .../git-man_1%3a2.30.2-1+deb11u2_all.deb ...
Unpacking git-man (1:2.30.2-1+deb11u2) ...
Selecting previously unselected package git.
Preparing to unpack .../git_1%3a2.30.2-1+deb11u2_armhf.deb ...
Unpacking git (1:2.30.2-1+deb11u2) ...
Setting up liberror-perl (0.17029-1) ...
Setting up git-man (1:2.30.2-1+deb11u2) ...
Setting up git (1:2.30.2-1+deb11u2) ...
Processing triggers for man-db (2.9.4-2) ...
Cloning into '/opt/pirrot'...
remote: Enumerating objects: 3511, done.
remote: Counting objects: 100% (731/731), done.
remote: Compressing objects: 100% (323/323), done.
remote: Total 3511 (delta 429), reused 690 (delta 396), pack-reused 2780
Receiving objects: 100% (3511/3511), 2.99 MiB | 993.00 KiB/s, done.
Resolving deltas: 100% (2027/2027), done.
Installing Pirrot...
Get:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease [15.0 kB]
Get:2 http://archive.raspberrypi.org/debian bullseye InRelease [23.6 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages [13.2 MB]
Get:4 http://archive.raspberrypi.org/debian bullseye/main armhf Packages [313 kB]
Fetched 13.6 MB in 28s (485 kB/s)
Reading package lists... Done
OS detected: raspbian 11
11 (bullseye)
VERSION_CODENAME=bullseye
Running version specific installer steps...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20210119).
lsb-release is already the newest version (11.1.0+rpi1).
lsb-release set to manually installed.
wget is already the newest version (1.21-1+deb11u1).
wget set to manually installed.
The following additional packages will be installed:
  gir1.2-glib-2.0 gir1.2-packagekitglib-1.0 libappstream4
  libgirepository-1.0-1 libglib2.0-0 libglib2.0-bin libglib2.0-data
  libpackagekit-glib2-18 libstemmer0d packagekit packagekit-tools python3-dbus
  python3-distro-info python3-gi python3-pycurl python3-software-properties
  unattended-upgrades
Suggested packages:
  appstream python-dbus-doc python3-dbus-dbg libcurl4-gnutls-dev
  python-pycurl-doc python3-pycurl-dbg bsd-mailx default-mta
  | mail-transport-agent needrestart powermgmt-base
Recommended packages:
  shared-mime-info xdg-user-dirs
The following NEW packages will be installed:
  apt-transport-https gir1.2-glib-2.0 gir1.2-packagekitglib-1.0 libappstream4
  libgirepository-1.0-1 libglib2.0-bin libglib2.0-data libpackagekit-glib2-18
  libstemmer0d packagekit packagekit-tools python3-dbus python3-distro-info
  python3-gi python3-pycurl python3-software-properties
  software-properties-common unattended-upgrades
The following packages will be upgraded:
  libglib2.0-0
1 upgraded, 18 newly installed, 0 to remove and 23 not upgraded.
Need to get 4,489 kB of archives.
After this operation, 17.2 MB of additional disk space will be used.
Get:1 http://mirror.netzwerge.de/raspbian/raspbian bullseye/main armhf apt-transport-https all 2.2.4 [160 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libglib2.0-0 armhf 2.66.8-1+deb11u1 [1,186 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libgirepository-1.0-1 armhf 1.66.1-1+b1 [82.6 kB]
Get:4 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf gir1.2-glib-2.0 armhf 1.66.1-1+b1 [151 kB]
Get:5 http://mirror.netzwerge.de/raspbian/raspbian bullseye/main armhf libpackagekit-glib2-18 armhf 1.2.2-2 [107 kB]
Get:6 http://mirror.netzwerge.de/raspbian/raspbian bullseye/main armhf gir1.2-packagekitglib-1.0 armhf 1.2.2-2 [36.7 kB]
Get:7 http://mirror.netzwerge.de/raspbian/raspbian bullseye/main armhf libstemmer0d armhf 2.1.0-1 [100 kB]
Get:8 http://mirror.netzwerge.de/raspbian/raspbian bullseye/main armhf libappstream4 armhf 0.14.4-1 [145 kB]
Get:9 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libglib2.0-data all 2.66.8-1+deb11u1 [1,177 kB]
Get:10 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libglib2.0-bin armhf 2.66.8-1+deb11u1 [135 kB]
Get:11 http://mirror.netzwerge.de/raspbian/raspbian bullseye/main armhf packagekit armhf 1.2.2-2 [557 kB]
Get:12 http://mirror.netzwerge.de/raspbian/raspbian bullseye/main armhf packagekit-tools armhf 1.2.2-2 [39.4 kB]
Get:13 http://mirror.netzwerge.de/raspbian/raspbian bullseye/main armhf python3-dbus armhf 1.2.16-5 [100 kB]
Get:14 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf python3-distro-info all 1.0+deb11u1 [8,860 B]
Get:15 http://mirror.netzwerge.de/raspbian/raspbian bullseye/main armhf python3-gi armhf 3.38.0-2 [215 kB]
Get:16 http://mirror.netzwerge.de/raspbian/raspbian bullseye/main armhf python3-pycurl armhf 7.43.0.6-5 [66.7 kB]
Get:17 http://mirror.netzwerge.de/raspbian/raspbian bullseye/main armhf python3-software-properties all 0.96.20.2-2.1 [49.7 kB]
Get:18 http://mirror.netzwerge.de/raspbian/raspbian bullseye/main armhf software-properties-common all 0.96.20.2-2.1 [83.4 kB]
Get:19 http://mirror.netzwerge.de/raspbian/raspbian bullseye/main armhf unattended-upgrades all 2.8 [88.6 kB]
Fetched 4,489 kB in 4s (1,094 kB/s)
apt-listchanges: Reading changelogs...
Preconfiguring packages ...
Selecting previously unselected package apt-transport-https.
(Reading database ... 44916 files and directories currently installed.)
Preparing to unpack .../00-apt-transport-https_2.2.4_all.deb ...
Unpacking apt-transport-https (2.2.4) ...
Preparing to unpack .../01-libglib2.0-0_2.66.8-1+deb11u1_armhf.deb ...
Unpacking libglib2.0-0:armhf (2.66.8-1+deb11u1) over (2.66.8-1) ...
Selecting previously unselected package libgirepository-1.0-1:armhf.
Preparing to unpack .../02-libgirepository-1.0-1_1.66.1-1+b1_armhf.deb ...
Unpacking libgirepository-1.0-1:armhf (1.66.1-1+b1) ...
Selecting previously unselected package gir1.2-glib-2.0:armhf.
Preparing to unpack .../03-gir1.2-glib-2.0_1.66.1-1+b1_armhf.deb ...
Unpacking gir1.2-glib-2.0:armhf (1.66.1-1+b1) ...
Selecting previously unselected package libpackagekit-glib2-18:armhf.
Preparing to unpack .../04-libpackagekit-glib2-18_1.2.2-2_armhf.deb ...
Unpacking libpackagekit-glib2-18:armhf (1.2.2-2) ...
Selecting previously unselected package gir1.2-packagekitglib-1.0.
Preparing to unpack .../05-gir1.2-packagekitglib-1.0_1.2.2-2_armhf.deb ...
Unpacking gir1.2-packagekitglib-1.0 (1.2.2-2) ...
Selecting previously unselected package libstemmer0d:armhf.
Preparing to unpack .../06-libstemmer0d_2.1.0-1_armhf.deb ...
Unpacking libstemmer0d:armhf (2.1.0-1) ...
Selecting previously unselected package libappstream4:armhf.
Preparing to unpack .../07-libappstream4_0.14.4-1_armhf.deb ...
Unpacking libappstream4:armhf (0.14.4-1) ...
Selecting previously unselected package libglib2.0-data.
Preparing to unpack .../08-libglib2.0-data_2.66.8-1+deb11u1_all.deb ...
Unpacking libglib2.0-data (2.66.8-1+deb11u1) ...
Selecting previously unselected package libglib2.0-bin.
Preparing to unpack .../09-libglib2.0-bin_2.66.8-1+deb11u1_armhf.deb ...
Unpacking libglib2.0-bin (2.66.8-1+deb11u1) ...
Selecting previously unselected package packagekit.
Preparing to unpack .../10-packagekit_1.2.2-2_armhf.deb ...
Unpacking packagekit (1.2.2-2) ...
Selecting previously unselected package packagekit-tools.
Preparing to unpack .../11-packagekit-tools_1.2.2-2_armhf.deb ...
Unpacking packagekit-tools (1.2.2-2) ...
Selecting previously unselected package python3-dbus.
Preparing to unpack .../12-python3-dbus_1.2.16-5_armhf.deb ...
Unpacking python3-dbus (1.2.16-5) ...
Selecting previously unselected package python3-distro-info.
Preparing to unpack .../13-python3-distro-info_1.0+deb11u1_all.deb ...
Unpacking python3-distro-info (1.0+deb11u1) ...
Selecting previously unselected package python3-gi.
Preparing to unpack .../14-python3-gi_3.38.0-2_armhf.deb ...
Unpacking python3-gi (3.38.0-2) ...
Selecting previously unselected package python3-pycurl.
Preparing to unpack .../15-python3-pycurl_7.43.0.6-5_armhf.deb ...
Unpacking python3-pycurl (7.43.0.6-5) ...
Selecting previously unselected package python3-software-properties.
Preparing to unpack .../16-python3-software-properties_0.96.20.2-2.1_all.deb ...
Unpacking python3-software-properties (0.96.20.2-2.1) ...
Selecting previously unselected package software-properties-common.
Preparing to unpack .../17-software-properties-common_0.96.20.2-2.1_all.deb ...
Unpacking software-properties-common (0.96.20.2-2.1) ...
Selecting previously unselected package unattended-upgrades.
Preparing to unpack .../18-unattended-upgrades_2.8_all.deb ...
Unpacking unattended-upgrades (2.8) ...
Setting up apt-transport-https (2.2.4) ...
Setting up libglib2.0-0:armhf (2.66.8-1+deb11u1) ...
No schema files found: doing nothing.
Setting up libpackagekit-glib2-18:armhf (1.2.2-2) ...
Setting up python3-pycurl (7.43.0.6-5) ...
Setting up libglib2.0-data (2.66.8-1+deb11u1) ...
Setting up python3-software-properties (0.96.20.2-2.1) ...
Setting up libgirepository-1.0-1:armhf (1.66.1-1+b1) ...
Setting up libstemmer0d:armhf (2.1.0-1) ...
Setting up python3-distro-info (1.0+deb11u1) ...
Setting up python3-dbus (1.2.16-5) ...
Setting up libglib2.0-bin (2.66.8-1+deb11u1) ...
Setting up libappstream4:armhf (0.14.4-1) ...
Setting up unattended-upgrades (2.8) ...

Creating config file /etc/apt/apt.conf.d/20auto-upgrades with new version

Creating config file /etc/apt/apt.conf.d/50unattended-upgrades with new version
Created symlink /etc/systemd/system/multi-user.target.wants/unattended-upgrades.service → /lib/systemd/system/unattended-upgrades.service.
Synchronizing state of unattended-upgrades.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable unattended-upgrades
Setting up gir1.2-glib-2.0:armhf (1.66.1-1+b1) ...
Setting up packagekit (1.2.2-2) ...
Created symlink /etc/systemd/user/sockets.target.wants/pk-debconf-helper.socket → /usr/lib/systemd/user/pk-debconf-helper.socket.
Setting up packagekit-tools (1.2.2-2) ...
Setting up gir1.2-packagekitglib-1.0 (1.2.2-2) ...
Setting up python3-gi (3.38.0-2) ...
Setting up software-properties-common (0.96.20.2-2.1) ...
Processing triggers for libc-bin (2.31-13+rpt2+rpi1+deb11u7) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for dbus (1.12.28-0+deb11u1) ...
++ whoami
+ '[' root '!=' root ']'
+ apt-get update
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Reading package lists... Done
+ apt-get -y install lsb-release ca-certificates curl
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20210119).
lsb-release is already the newest version (11.1.0+rpi1).
The following additional packages will be installed:
  libcurl4
The following packages will be upgraded:
  curl libcurl4
2 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
Need to get 569 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf curl armhf 7.74.0-1.3+deb11u11 [259 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libcurl4 armhf 7.74.0-1.3+deb11u11 [310 kB]
Fetched 569 kB in 1s (576 kB/s)
apt-listchanges: Reading changelogs...
(Reading database ... 45456 files and directories currently installed.)
Preparing to unpack .../curl_7.74.0-1.3+deb11u11_armhf.deb ...
Unpacking curl (7.74.0-1.3+deb11u11) over (7.74.0-1.3+deb11u10) ...
Preparing to unpack .../libcurl4_7.74.0-1.3+deb11u11_armhf.deb ...
Unpacking libcurl4:armhf (7.74.0-1.3+deb11u11) over (7.74.0-1.3+deb11u10) ...
Setting up libcurl4:armhf (7.74.0-1.3+deb11u11) ...
Setting up curl (7.74.0-1.3+deb11u11) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for libc-bin (2.31-13+rpt2+rpi1+deb11u7) ...
+ curl -sSLo /tmp/debsuryorg-archive-keyring.deb https://packages.sury.org/debsuryorg-archive-keyring.deb
+ dpkg -i /tmp/debsuryorg-archive-keyring.deb
Selecting previously unselected package debsuryorg-archive-keyring.
(Reading database ... 45456 files and directories currently installed.)
Preparing to unpack .../debsuryorg-archive-keyring.deb ...
Unpacking debsuryorg-archive-keyring (2024.02.05+0~20240205.1+debian12~1.gbp343037) ...
Setting up debsuryorg-archive-keyring (2024.02.05+0~20240205.1+debian12~1.gbp343037) ...
+ sh -c 'echo "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
+ apt-get update
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Get:3 https://packages.sury.org/php bullseye InRelease [7,551 B]
Get:4 https://packages.sury.org/php bullseye/main armhf Packages [236 kB]
Fetched 244 kB in 5s (46.6 kB/s)
Reading package lists... Done
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:3 https://packages.sury.org/php bullseye InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
26 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  libabsl20200923 libaom0 libavif9 libdav1d4 libde265-0 libgav1-0 libheif1
  libx265-192
The following packages will be upgraded:
  base-files bind9-host bind9-libs bluez cifs-utils distro-info-data
  libbluetooth3 libcurl3-gnutls libgd3 libgnutls30 libmpdec3 libnftables1
  libpcre2-8-0 libpcre3 libperl5.32 libxml2 nftables openssh-client
  openssh-server openssh-sftp-server perl perl-base perl-modules-5.32 ssh tar
  tzdata
26 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
Need to get 18.8 MB of archives.
After this operation, 8,462 kB of additional disk space will be used.
Get:1 http://archive.raspberrypi.org/debian bullseye/main armhf bluez armhf 5.55-3.1+rpt2+deb11u1 [844 kB]
Get:5 http://archive.raspberrypi.org/debian bullseye/main armhf libbluetooth3 armhf 5.55-3.1+rpt2+deb11u1 [106 kB]
Get:7 https://packages.sury.org/php bullseye/main armhf libpcre3 armhf 2:8.45-1+0~20230620.10+debian11~1.gbp8792c4 [322 kB]
Get:9 https://packages.sury.org/php bullseye/main armhf libpcre2-8-0 armhf 10.40-1+0~20220713.16+debian11~1.gbpb6cec5 [225 kB]
Get:11 https://packages.sury.org/php bullseye/main armhf libxml2 armhf 2.9.14+dfsg-0.1+0~20230421.14+debian11~1.gbpf14485 [614 kB]
Get:13 https://packages.sury.org/php bullseye/main armhf libgd3 armhf 2.3.3-9+0~20230207.13+debian11~1.gbp649015 [121 kB]
Get:14 https://packages.sury.org/php bullseye/main armhf libmpdec3 armhf 2.5.1-2+0~20240210.5+debian11~1.gbp216c03 [75.1 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf base-files armhf 11.1+rpi1+deb11u9 [70.5 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libperl5.32 armhf 5.32.1-4+deb11u3 [3,387 kB]
Get:4 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf perl armhf 5.32.1-4+deb11u3 [293 kB]
Get:6 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf perl-base armhf 5.32.1-4+deb11u3 [1,434 kB]
Get:8 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf perl-modules-5.32 all 5.32.1-4+deb11u3 [2,823 kB]
Get:10 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf tar armhf 1.34+dfsg-1+deb11u1 [800 kB]
Get:12 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf nftables armhf 0.9.8-3.1+deb11u2 [68.2 kB]
Get:15 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libnftables1 armhf 0.9.8-3.1+deb11u2 [227 kB]
Get:16 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf openssh-sftp-server armhf 1:8.4p1-5+deb11u3 [42.8 kB]
Get:17 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf openssh-server armhf 1:8.4p1-5+deb11u3 [319 kB]
Get:18 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf openssh-client armhf 1:8.4p1-5+deb11u3 [796 kB]
Get:19 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf ssh all 1:8.4p1-5+deb11u3 [252 kB]
Get:20 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libgnutls30 armhf 3.7.1-5+deb11u4 [1,263 kB]
Get:21 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf tzdata all 2024a-0+deb11u1 [304 kB]
Get:22 http://mirror.netzwerge.de/raspbian/raspbian bullseye/main armhf bind9-libs armhf 1:9.16.48-1 [1,278 kB]
Get:23 http://mirror.netzwerge.de/raspbian/raspbian bullseye/main armhf bind9-host armhf 1:9.16.48-1 [310 kB]
Get:24 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf cifs-utils armhf 2:6.11-3.1+deb11u2 [85.2 kB]
Get:25 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf distro-info-data all 0.51+deb11u5 [8,244 B]
Get:26 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libabsl20200923 armhf 0~20200923.3-2 [312 kB]
Get:27 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libaom0 armhf 1.0.0.errata1-3+deb11u1 [767 kB]
Get:28 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libdav1d4 armhf 0.7.1-3+rpi1 [207 kB]
Get:29 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libgav1-0 armhf 0.16.0-5+rpi1 [266 kB]
Get:30 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libavif9 armhf 0.8.4-2+deb11u1 [51.7 kB]
Get:31 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libcurl3-gnutls armhf 7.74.0-1.3+deb11u11 [306 kB]
Get:32 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libde265-0 armhf 1.0.11-0+deb11u3+rpi1 [134 kB]
Get:33 http://mirror.netzwerge.de/raspbian/raspbian bullseye/main armhf libx265-192 armhf 3.4-2 [560 kB]
Get:34 http://mirror.netzwerge.de/raspbian/raspbian bullseye/main armhf libheif1 armhf 1.11.0-1 [161 kB]
Fetched 18.8 MB in 12s (1,545 kB/s)
apt-listchanges: Reading changelogs...
Extracting templates from packages: 100%
Preconfiguring packages ...
(Reading database ... 45467 files and directories currently installed.)
Preparing to unpack .../base-files_11.1+rpi1+deb11u9_armhf.deb ...
Unpacking base-files (11.1+rpi1+deb11u9) over (11.1+rpi1+deb11u8) ...
Setting up base-files (11.1+rpi1+deb11u9) ...
Installing new version of config file /etc/debian_version ...
(Reading database ... 45467 files and directories currently installed.)
Preparing to unpack .../libperl5.32_5.32.1-4+deb11u3_armhf.deb ...
Unpacking libperl5.32:armhf (5.32.1-4+deb11u3) over (5.32.1-4+deb11u2) ...
Preparing to unpack .../perl_5.32.1-4+deb11u3_armhf.deb ...
Unpacking perl (5.32.1-4+deb11u3) over (5.32.1-4+deb11u2) ...
Preparing to unpack .../perl-base_5.32.1-4+deb11u3_armhf.deb ...
Unpacking perl-base (5.32.1-4+deb11u3) over (5.32.1-4+deb11u2) ...
Setting up perl-base (5.32.1-4+deb11u3) ...
(Reading database ... 45467 files and directories currently installed.)
Preparing to unpack .../perl-modules-5.32_5.32.1-4+deb11u3_all.deb ...
Unpacking perl-modules-5.32 (5.32.1-4+deb11u3) over (5.32.1-4+deb11u2) ...
Preparing to unpack .../tar_1.34+dfsg-1+deb11u1_armhf.deb ...
Unpacking tar (1.34+dfsg-1+deb11u1) over (1.34+dfsg-1) ...
Setting up tar (1.34+dfsg-1+deb11u1) ...
(Reading database ... 45467 files and directories currently installed.)
Preparing to unpack .../0-nftables_0.9.8-3.1+deb11u2_armhf.deb ...
Unpacking nftables (0.9.8-3.1+deb11u2) over (0.9.8-3.1+deb11u1) ...
Preparing to unpack .../1-libnftables1_0.9.8-3.1+deb11u2_armhf.deb ...
Unpacking libnftables1:armhf (0.9.8-3.1+deb11u2) over (0.9.8-3.1+deb11u1) ...
Preparing to unpack .../2-bluez_5.55-3.1+rpt2+deb11u1_armhf.deb ...
Unpacking bluez (5.55-3.1+rpt2+deb11u1) over (5.55-3.1+rpt2) ...
Preparing to unpack .../3-openssh-sftp-server_1%3a8.4p1-5+deb11u3_armhf.deb ...
Unpacking openssh-sftp-server (1:8.4p1-5+deb11u3) over (1:8.4p1-5+deb11u2) ...
Preparing to unpack .../4-openssh-server_1%3a8.4p1-5+deb11u3_armhf.deb ...
Unpacking openssh-server (1:8.4p1-5+deb11u3) over (1:8.4p1-5+deb11u2) ...
Preparing to unpack .../5-openssh-client_1%3a8.4p1-5+deb11u3_armhf.deb ...
Unpacking openssh-client (1:8.4p1-5+deb11u3) over (1:8.4p1-5+deb11u2) ...
Preparing to unpack .../6-ssh_1%3a8.4p1-5+deb11u3_all.deb ...
Unpacking ssh (1:8.4p1-5+deb11u3) over (1:8.4p1-5+deb11u2) ...
Preparing to unpack .../7-libpcre3_2%3a8.45-1+0~20230620.10+debian11~1.gbp8792c4_armhf.deb ...
Unpacking libpcre3:armhf (2:8.45-1+0~20230620.10+debian11~1.gbp8792c4) over (2:8.39-13) ...
Setting up libpcre3:armhf (2:8.45-1+0~20230620.10+debian11~1.gbp8792c4) ...
(Reading database ... 45467 files and directories currently installed.)
Preparing to unpack .../libgnutls30_3.7.1-5+deb11u4_armhf.deb ...
Unpacking libgnutls30:armhf (3.7.1-5+deb11u4) over (3.7.1-5+deb11u3) ...
Setting up libgnutls30:armhf (3.7.1-5+deb11u4) ...
(Reading database ... 45467 files and directories currently installed.)
Preparing to unpack .../libpcre2-8-0_10.40-1+0~20220713.16+debian11~1.gbpb6cec5_armhf.deb ...
Unpacking libpcre2-8-0:armhf (10.40-1+0~20220713.16+debian11~1.gbpb6cec5) over (10.36-2+deb11u1) ...
Illegal instruction
E: Sub-process /usr/bin/dpkg exited unexpectedly
/opt/pirrot/build/scripts/os_versions/raspbian_11.install: line 5:  3999 Illegal instruction     sudo apt-get install -y sox morse lame php8.1-cli php8.1-curl php8.1-mbstring php8.1-sqlite3 php8.1-xml
 # Checking for Pirrot configuration...
 - Creating new pirrot.conf from template...
/opt/pirrot/build/scripts/install.sh: line 40:  4000 Illegal instruction     sudo cp /opt/pirrot/build/configs/pirrot_default.conf /etc/pirrot.conf
/opt/pirrot/build/scripts/install.sh: line 40:  4001 Illegal instruction     sudo chmod 0644 /etc/pirrot.conf
 # Installing the Pirrot Scheduler...
/opt/pirrot/build/scripts/install.sh: line 43:  4002 Illegal instruction     sudo cp /opt/pirrot/build/configs/pirrot_scheduler /etc/cron.d/pirrot
/opt/pirrot/build/scripts/install.sh: line 44:  4003 Illegal instruction     sudo chmod 0644 /etc/cron.d/pirrot
 # Checking for Pirrot Web Interface configuration...
 - Setting default configuration for Pirrot Web interface...
/opt/pirrot/build/scripts/install.sh: line 50:  4004 Illegal instruction     sudo cp /opt/pirrot/web/.env.example /opt/pirrot/web/.env
 # Checking if log files exist...
 - Creating log file and setting permissions...
/opt/pirrot/build/scripts/install.sh: line 59:  4005 Illegal instruction     sudo touch /var/log/pirrot.log
/opt/pirrot/build/scripts/install.sh: line 59:  4006 Illegal instruction     sudo chmod 0644 /var/log/pirrot.log
/opt/pirrot/build/scripts/install.sh: line 59:  4007 Illegal instruction     sudo touch /var/log/pirrot-web.log
/opt/pirrot/build/scripts/install.sh: line 59:  4008 Illegal instruction     sudo chmod 0644 /var/log/pirrot-web.log
 - Setting execution bit on /opt/pirrot/pirrot...
/opt/pirrot/build/scripts/install.sh: line 63:  4009 Illegal instruction     sudo chmod +x /opt/pirrot/pirrot
/opt/pirrot/build/scripts/install.sh: line 66:  4010 Illegal instruction     sudo ln -s /opt/pirrot/pirrot /usr/local/bin/pirrot
/opt/pirrot/build/scripts/install.sh: line 69:  4011 Illegal instruction     sudo mkdir /opt/pirrot/storage
/opt/pirrot/build/scripts/install.sh: line 70:  4012 Illegal instruction     sudo mkdir /opt/pirrot/storage/input
/opt/pirrot/build/scripts/install.sh: line 71:  4013 Illegal instruction     sudo mkdir /opt/pirrot/storage/recordings
/opt/pirrot/build/scripts/install.sh: line 72:  4014 Illegal instruction     sudo mkdir /opt/pirrot/storage/backups
/opt/pirrot/build/scripts/install.sh: line 73:  4015 Illegal instruction     sudo mkdir /opt/pirrot/storage/tts
/opt/pirrot/build/scripts/install.sh: line 74:  4016 Illegal instruction     sudo chmod -R 755 /opt/pirrot/storage
 - Creating empty Pirrot Web database...
/opt/pirrot/build/scripts/install.sh: line 80:  4017 Illegal instruction     sudo touch /opt/pirrot/storage/pirrot-web.database
 - Linking the recordings directory to the admin web interface...
/opt/pirrot/build/scripts/install.sh: line 86:  4018 Illegal instruction     sudo ln -s /opt/pirrot/storage/recordings/ /opt/pirrot/web/public/recordings
 - Setting default password for Pirrot Web interface...
/opt/pirrot/build/scripts/install.sh: line 92:  4019 Illegal instruction     sudo cp /opt/pirrot/build/configs/default_password.vault /opt/pirrot/storage/password.vault
 - Installing the daemon...
/opt/pirrot/build/scripts/install.sh: line 96:  4020 Illegal instruction     sudo cp /opt/pirrot/build/init.d/pirrot /etc/init.d/pirrot
/opt/pirrot/build/scripts/install.sh: line 97:  4021 Illegal instruction     sudo chmod +x /etc/init.d/pirrot
/opt/pirrot/build/scripts/install.sh: line 98:  4022 Illegal instruction     sudo update-rc.d pirrot defaults
 - Installing Composer...
/opt/pirrot/build/scripts/install.sh: line 102:  4023 Illegal instruction     wget https://getcomposer.org/composer.phar
/opt/pirrot/build/scripts/install.sh: line 103:  4024 Illegal instruction     sudo mv composer.phar /usr/bin/composer
/opt/pirrot/build/scripts/install.sh: line 104:  4025 Illegal instruction     sudo chmod +x /usr/bin/composer
/opt/pirrot/build/scripts/install.sh: line 105:  4026 Illegal instruction     sudo /usr/bin/composer self-update
 - Installing Pirrot Dependencies...
/opt/pirrot/build/scripts/install.sh: line 109:  4027 Illegal instruction     sudo composer install -q --working-dir /opt/pirrot --no-dev --no-interaction
/opt/pirrot/build/scripts/install.sh: line 110:  4028 Illegal instruction     sudo composer install -q --working-dir /opt/pirrot/web --no-dev --no-interaction
 - Running database updates...
/opt/pirrot/build/scripts/install.sh: line 114:  4029 Illegal instruction     sudo /usr/bin/php /opt/pirrot/web/artisan migrate --force
 - Disabling on-board audio device
/opt/pirrot/build/scripts/install.sh: line 118:  4030 Illegal instruction     sudo sed -i "s|options snd-usb-audio index=-2|#options snd-usb-audio index=-2|" /lib/modprobe.d/aliases.conf
/opt/pirrot/build/scripts/install.sh: line 119:  4031 Done                    echo "blacklist snd_bcm2835"
      4032 Illegal instruction     | sudo tee -a /etc/modprobe.d/raspi-blacklist.conf
Do you want to enable the admin web interface? (y/n)? y/opt/pirrot/build/scripts/install.sh: line 138:  4033 Illegal instruction     sed -i "s|web_interface_enabled = false|web_interface_enabled = true|" /etc/pirrot.conf

 **Web interface has been enabled!**

The default credentials are:

    URL:      http://{IP_ADDRESS}:8440
    Username: admin
    Password: pirrot

You can reset the password at anytime using the following command:

 sudo pirrot setwebpwd --password={YourPasswordHere}


Please reboot your RaspberryPi now to enable Pirrot!

Restart your device now (y/n)? y
/opt/pirrot/build/scripts/install.sh: line 151:  4034 Illegal instruction     sudo shutdown -r now
make: *** [Makefile:2: install] Error 132
pi@pirrot:/opt/pirrot $
```

**Comment by ComputerCarsten** [comment]
I found out that the packages.sury.org repository causes this. While googling I found some statements that 'armhf' in debian relates to armv7 and in rasbian to armv6 with floating point unit. The PI zero is ARM V6.

If I comment it out and replace the php8.1 with php8.0 in the raspbian_11.install file, it does not throw the Illegal Instruction errors anymore. Now a new problem with an 'composer rolled back' and some composer packages not found comes up.

**Comment by ja5aea** [comment]
Hi Greeting.

I am a newbie and finished the assembling of interface circuits and connection with 2m radio and rp zero w v1.1 along with 8GByte SD card and confirmed the proper work with tester and oscilloscope as much as possible spending a week.

Then, I followed the instruction and finished the latest  OS 12 and Pirrot  latest-stable installation works. But nothing happens except proper SSH connection to the rp. 

Now, I noticed the similar error messages before "web interface enabling" process in Pirrot insttalation written in this thread.

Can I ask the latest issue status at this moment?

Thank you.

Regards,

take

de JA5AEA

**Comment by ja5aea** [comment]
Hi Bobby,

Today, I made a little progress.

Pirrot installation work extended more than one hour by 16GByte SD card and the following is the last end of installattion log.  

Is this the proper ending of the installation?

This works are done on OS12. I experienced OS panic as "ComputerCarsten" describes if I do ir on OS11. 
It is unfortunate that I  can still see four "Illegal instalation" lines.

---------------------------------------------------------------------------------------------
2024-08-15 15:03:48 (1.04 MB/s) - ‘composer.phar’ saved [3011317/3011317]

/opt/pirrot/build/scripts/install.sh: line 105: 22495 Illegal instruction     sudo /usr/bin/composer self-update
 - Installing Pirrot Dependencies...
/opt/pirrot/build/scripts/install.sh: line 109: 22498 Illegal instruction     sudo composer install -q --working-dir /opt/pirrot --no-dev --no-interaction
/opt/pirrot/build/scripts/install.sh: line 110: 22501 Illegal instruction     sudo composer install -q --working-dir /opt/pirrot/web --no-dev --no-interaction
 - Running database updates...
/opt/pirrot/build/scripts/install.sh: line 114: 22504 Illegal instruction     sudo /usr/bin/php /opt/pirrot/web/artisan migrate --force
 - Disabling on-board audio device
blacklist snd_bcm2835

Do you want to enable the admin web interface? (y/n)? y
 **Web interface has been enabled!**

The default credentials are:

    URL:      http://{IP_ADDRESS}:8440
    Username: admin
    Password: pirrot

You can reset the password at anytime using the following command:

 sudo pirrot setwebpwd --password={YourPasswordHere}


Please reboot your RaspberryPi now to enable Pirrot!

Restart your device now (y/n)? n
---------------------------------------------------------------------------------------------

After the reboot, I could not still recognize the pirrot works or notsuch as  by PTT LED coulr change or actual radio PTT activation.

The following is systemd status command. (Sorry it is difficult to read by UTF language difference.)

---------------------------------------------------------------------------------------------
sudo systemctl status pirrot
[?2004l

[0;1;32m●[0m pirrot.service - LSB: The Pirrot Repeater Daemon[m
     Loaded: loaded (]8;;file://pirrot/etc/init.d/pirrot/etc/init.d/pirrot]8;;; generated[0;1;32m[0m)[m
     Active: [0;1;32mactive (exited)[0m since Thu 2024-08-15 15:25:20 JST; 7min ago[m
       Docs: ]8;;man:systemd-sysv-generator(8)man:systemd-sysv-generator(8)]8;;[m
    Process: 326 ExecStart=/etc/init.d/pirrot start (code=exited, status=0/SUCCESS)[m
        CPU: 400ms[m
[m
Aug 15 15:25:18 pirrot systemd[1]: Starting pirrot.service - LSB: The Pirrot Repeater Daemon...[m
Aug 15 15:25:18 pirrot pirrot[326]: Starting Pirrot...[m
Aug 15 15:25:18 pirrot pirrot[326]: done![m
Aug 15 15:25:20 pirrot systemd[1]: Started pirrot.service - LSB: The Pirrot Repeater Daemon.[m

[K[?2004h[01;32mjs1mav@pirrot[00m:[01;34m~ $[00m exit
[?2004l
---------------------------------------------------------------------------------------------

Any suggestion?

I am waiting your response soon.

Regards,

take

de JA5AEA

**Comment by tapaizoltan** [comment]
Hi!

I installed it on a zero w. but the web admin won't start. Whatever command I give, it says illegal instruction. What could be the problem?
